name: BasicCircuits
main: org.tal.basiccircuits.BasicCircuits
version: 0.82
author: eisental
description: Basic circuit library for RedstoneChips integrated circuits plugin.
website: eisental.github.com/RedstoneChips
depend: RedstoneChips-0.82.jar